server:
  port: 8180
  servlet:
    context-path: /spring-boot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dstudents
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create